services:
    loadbalancer:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/logs:/var/log/nginx
        networks:
            - webnet
        depends_on:
            - webserver1
            - webserver2
            - webserver3

    webserver1:
        image: nginx:latest
        volumes:
            - ./nginx/html:/usr/share/nginx/html:ro
            - ./nginx/nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/logs:/var/log/nginx
        networks:
            - webnet

    webserver2:
        image: nginx:latest
        volumes:
            - ./nginx/html:/usr/share/nginx/html:ro
            - ./nginx/nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/logs:/var/log/nginx
        networks:
            - webnet

    webserver3:
        image: nginx:latest
        volumes:
            - ./nginx/html:/usr/share/nginx/html:ro
            - ./nginx/nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/logs:/var/log/nginx
        networks:
            - webnet

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - webnet

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - webnet

    filebeat:
        image: elastic/filebeat:8.11.1
        user: root
        volumes:
            - ./nginx/logs:/var/log/nginx:ro
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        command: filebeat -e -strict.perms=false
        networks:
            - webnet
        depends_on:
            - kafka

    cassandra:
        image: cassandra:latest
        ports:
            - '9042:9042'
        networks:
            - webnet
        environment:
            - CASSANDRA_CLUSTER_NAME=WebLogCluster

networks:
    webnet:
